version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: tareas_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tareas_familiares
    ports:
      - "5432:5432"
    volumes:
      - tareas_pg_data:/var/lib/postgresql/data

volumes:
  tareas_pg_data:
